### ISSUE TITLE
Forge Installation doesn't allow keybind to work

### ISSUE THREAD

**Issue by FatCat1978** [thedirptastic/SquakeFabric#2]
Mod list:

(Forge) 1.20.1 simple neon lights mod v2.2.jar
1.20.1-forge-5.3.10+1.20.1b46-BETA-forge.jar
AdChimneys-1.20.1-10.1.15.0-build.0828.jar
additional_lights-1.20.1-2.1.7.jar
AdPoles-1.20.1-9.1.1.0-build.0473.jar
AdvancedPeripherals-1.20.1-0.7.40r.jar
AdvancementPlaques-1.20.1-forge-1.6.7.jar
ad_astra-forge-1.20.1-1.15.18.jar
aether-1.20.1-1.4.2-neoforge.jar
AI-Improvements-1.20-0.5.2.jar
alexscaves-1.1.5.jar
alexscavestrimmed-1.1.0.jar
alexsdelight-1.5.jar
alexsmobs-1.22.9.jar
amendments-1.20-1.2.11.jar
appleskin-forge-mc1.20.1-2.5.1.jar
appliedenergistics2-forge-15.2.13.jar
Aquaculture-1.20.1-2.5.2.jar
Architects-Palette-1.20.1-1.3.6.1.jar
architectury-9.2.14-forge.jar
argonauts-forge-1.20.1-1.0.10.jar
ars_nouveau-1.20.1-4.12.4-all.jar
artifacts-forge-9.5.13.jar
athena-forge-1.20.1-3.1.2.jar
AttributeFix-Forge-1.20.1-21.0.4.jar
automobility-0.4.2+1.20.1-forge.jar
awesomedungeonocean-forge-1.20.1-3.3.0.jar
azurelib-neo-1.20.1-2.0.39.jar
backpacked-forge-1.20.1-2.2.5.jar
balancedflight-1.20.1_v2.3.0.jar
balm-forge-1.20.1-7.3.9-all.jar
bellsandwhistles-0.4.3-1.20.x.jar
benssharks-1.2.4.9-forge-1.20.1.jar
betterchunkloading-1.20.1-4.5.jar
betterendcities-1.0.0-1.20.1.jar
BetterPingDisplay-1.20.1-1.1.jar
Bookshelf-Forge-1.20.1-20.2.13.jar
Botania-1.20.1-446-FORGE.jar
botarium-forge-1.20.1-2.3.4.jar
BuildGuide-1.20-0.4.3.jar
buildinggadgets2-1.0.7.jar
caelus-forge-3.2.0+1.20.1.jar
camera-forge-1.20.1-1.0.14.jar
canary-mc1.20.1-0.3.3.jar
cat_jam-forge-mc1.20-1.2.2.jar
cc-tweaked-1.20.1-forge-1.113.1.jar
cccbridge-mc1.20.1-forge-1.6.3.jar
Chipped-forge-1.20.1-3.0.6.jar
chunksending-1.20.1-2.8.jar
Chunky-1.3.146.jar
citadel-2.6.0-1.20.1.jar
clickadv-1.20.1-3.8.jar
clientcrafting-1.20.1-1.8.jar
cloth-config-11.1.136-forge.jar
Clumps-forge-1.20.1-12.0.0.4.jar
cofh_core-1.20.1-11.0.2.56.jar
collective-1.20.1-7.84.jar
comforts-forge-6.4.0+1.20.1.jar
configured-forge-1.20.1-2.2.3.jar
connectivity-1.20.1-5.6.jar
constructionwand-1.20.1-2.11.jar
Controlling-forge-1.20.1-12.0.2.jar
corail_woodcutter-1.20.1-3.0.6.jar
coroutil-forge-1.20.1-1.3.7.jar
corpse-forge-1.20.1-1.0.14.jar
create-1.20.1-0.5.1.h.jar
create-new-age-forge-1.20.1-1.1.2.jar
create-stuff-additions1.20.1_v2.0.4a.jar
createbicbit-1.20.1-0.0.86.jar
createbigcannons-5.5.1-mc.1.20.1-forge.jar
createdeco-2.0.2-1.20.1-forge.jar
createliquidfuel-2.1.1-1.20.1.jar
create_central_kitchen-1.20.1-for-create-0.5.1.f-1.3.12.jar
create_connected-0.9.1-mc1.20.1-all.jar
create_enchantment_industry-1.20.1-for-create-0.5.1.f-1.2.9.d.jar
create_oppenheimered-1.0.3.jar
CreativeCore_FORGE_v2.12.17_mc1.20.1.jar
cupboard-1.20.1-2.7.jar
curios-forge-5.10.0+1.20.1.jar
curios-neoforge-9.0.11+1.21.jar
customizableelytra-forge-2.1.2+1.20.jar
decorative_blocks-forge-1.20.1-4.1.3.jar
deeperdarker-forge-1.20.1-1.3.2.jar
design_decor-0.4.0b-1.20.1.jar
Ding-1.20.1-Forge-1.5.0.jar
dir.txt
Display Case-forge-1.20-1.0.8.jar
DistantHorizons-2.2.1-a-1.20.1-forge-fabric.jar
dummmmmmy-1.20-2.0.2.jar
Dungeon Crawl-1.20.1-2.3.14.jar
DungeonsAriseSevenSeas-1.20.x-1.0.2-forge.jar
DustrialDecor-1.3.5-1.20.jar
embeddium-0.3.31+mc1.20.1.jar
emi-1.1.14+1.20.1+forge.jar
EnchantmentDescriptions-Forge-1.20.1-17.1.18.jar
endersdelight-1.20.1-1.0.3.jar
ender_chested-1.20.1-1.1.0.jar
endrem_forge-5.3.3-R-1.20.1.jar
experimentalsettingsdisabler-1.20.1-3.0.jar
fairylights-7.0.0-1.20.1.jar
Fallingleaves-1.20.1-2.1.0.jar
FarmersDelight-1.20.1-1.2.4.jar
fast-ip-ping-v1.0.5-mc1.20.4-forge.jar
FastFurnace-1.20.1-8.0.2.jar
FastLeafDecay-32.jar
Fastload-Reforged-mc1.20.1-3.4.0.jar
FastWorkbench-1.20.1-8.0.4.jar
ferritecore-6.0.1-forge.jar
ForgeEndertech-1.20.1-11.1.4.0-build.0572.jar
FramedBlocks-9.3.1.jar
framework-forge-1.20.1-0.7.8.jar
freecam-forge-1.2.1+1.20.jar
ftb-chunks-forge-2001.3.1.jar
ftb-essentials-forge-2001.2.2.jar
ftb-library-forge-2001.2.4.jar
ftb-teams-forge-2001.3.0.jar
ftbbackups2-forge-1.20-1.0.23.jar
fusion-1.1.1-forge-mc1.20.1.jar
geckolib-forge-1.20.1-4.4.9.jar
global_packs-forge-1.19.4-1.16.2_forge.jar
GoProne-forge-1.20.1-3.1.1.jar
gourmet-0.1.1b-1.20.1.jar
handcrafted-forge-1.20.1-3.0.6.jar
Highlighter-1.20.1-forge-1.1.9.jar
iceandfire-2.1.13-1.20.1-beta-5.jar
Iceberg-1.20.1-forge-1.1.21.jar
iChunUtil-1.20.1-Forge-1.0.0.jar
idas_forge-1.10.1+1.20.1.jar
ImmediatelyFast-Forge-1.2.21+1.20.4.jar
immersive_aircraft-1.1.2+1.20.1-forge.jar
infinitybuttons-1.20.1-4.0.4.jar
integrated_api-1.5.1+1.20.1-forge.jar
interiors-0.5.6+forge-mc1.20.1-build.104.jar
ironchest-1.20.1-14.4.4.jar
irons_spellbooks-1.20.1-3.4.0.2.jar
Jade-1.20.1-forge-11.11.1.jar
jecalculation-forge-1.20.1-4.0.4.jar
jei-1.20.1-forge-15.20.0.102.jar
JustEnoughProfessions-forge-1.20.1-3.0.1.jar
JustEnoughResources-1.20.1-1.4.0.247.jar
kotlinforforge-4.11.0-all.jar
kubejs-create-forge-2001.2.5-build.2.jar
kubejs-forge-2001.6.5-build.14.jar
LegendaryTooltips-1.20.1-forge-1.4.5.jar
letsdo-API-forge-1.2.15-forge.jar
letsdo-vinery-forge-1.4.28.jar
libraryferret-forge-1.20.1-4.0.0.jar
light-overlay-8.0.0-forge.jar
LittleTiles_BETA_v1.6.0-pre131_mc1.20.1.jar.disabled
logprot-1.20.1-3.4.jar
lootintegrations-1.20.1-3.7.jar
lootr-forge-1.20-0.7.34.89.jar
MaFgLib-0.1.13-mc1.20.1.jar
MagnumTorch-v8.0.2-1.20.1-Forge.jar
mcjtylib-1.20-8.0.6.jar
mcw-bridges-3.0.0-mc1.20.1forge.jar
mcw-doors-1.1.1forge-mc1.20.1.jar
mcw-fences-1.1.2-mc1.20.1forge.jar
mcw-lights-1.1.0-mc1.20.1forge.jar
mcw-trapdoors-1.1.3-mc1.20.1forge.jar
Measurements-forge-1.20.1-2.0.0.jar
mechanicalbotania-1.0.1.jar
mes-1.3.1-1.20-forge.jar
mffs-5.1.9-all.jar
mods_optimizer-forge-1.20.1-2.0.0.jar
moonlight-1.20-2.13.2-forge.jar
MorePeripherals_1.20.1-1.13.0.jar
morered-1.20.1-4.0.0.4.jar
MoreRed-CCT-Compat-1.20.1-1.0.0.jar
MouseTweaks-forge-mc1.20.1-2.25.1.jar
mowziesmobs-1.6.5.jar
NaturesCompass-1.20.1-1.11.2-forge.jar
Necronomicon-Forge-1.6.0+1.20.1.jar
neoncraft-1.1.0.jar
netherportalfix-forge-1.20-13.0.1.jar
NoChatReports-FORGE-1.20.1-v2.2.2.jar
Not Enough Recipe Book-FORGE-0.4.1+1.20.1.jar
notenoughcrashes-4.4.7+1.20.1-forge.jar
notenoughwands-1.20-6.0.2.jar
Nullscape_1.20.x_v1.2.8.jar
OctoLib-FORGE-0.4.2+1.20.1.jar
oculus-flywheel-compat-forge1.20.1+1.1.2.jar.disabled
oculus-mc1.20.1-1.7.0.jar.disabled
okzoomer-forge-1.20-3.0.1.jar
packetfixer-forge-1.4.2-1.19-to-1.20.1.jar
Patchouli-1.20.1-84-FORGE.jar
Placebo-1.20.1-8.6.2.jar
player-animation-lib-forge-1.0.2-rc1+1.20.jar
polylib-forge-2000.0.3-build.143.jar
polymorph-forge-0.49.5+1.20.1.jar
ponderjs-1.20.1-1.4.0.jar
Prism-1.20.1-forge-1.0.5.jar
PuzzlesLib-v8.1.24-1.20.1-Forge.jar
Quark-4.0-460.jar
QuarkOddities-1.20.1.jar
Raided-1.20.1-0.1.4.jar
ramcompat-1.20.1-0.1.4.jar
refurbished_furniture-forge-1.20.1-1.0.6.jar
relics-1.20.1-0.8.0.7.jar
resourcefulconfig-forge-1.20.1-2.1.2.jar
resourcefullib-forge-1.20.1-2.1.29.jar
rhino-forge-2001.2.3-build.6.jar
right-click-harvest-3.2.3+1.20.1-forge.jar
rrls-4.0.6.1+mc1.20.1-forge.jar
Searchables-forge-1.20.1-1.0.3.jar
shulkerboxtooltip-forge-4.0.4+1.20.1.jar
simplylight-1.20.1-1.4.6-build.50.jar
skinlayers3d-forge-1.6.7-mc1.20.1.jar
sliceanddice-forge-3.3.0.jar
smallships-forge-1.20.1-2.0.0-b1.4.jar
smoothchunk-1.20.1-3.6.jar
sootychimneys-1.20.1-1.2.1.jar
sound-physics-remastered-forge-1.20.1-1.4.5.jar
spark-1.10.53-forge.jar
squakereforged-1.0-SNAPSHOT.jar
stalwart-dungeons-1.20.1-1.2.8.jar
Steam_Rails-1.6.5+forge-mc1.20.1.jar
StorageDrawers-1.20.1-12.7.2.jar
Structory_Towers_1.20.x_v1.0.7.jar
supplementaries-1.20-2.8.17.jar
tectonic-forge-1.20.1-2.4.1.jar
Terralith_1.20.x_v2.5.4.jar
tfmg-0.9.2-1.20.1.jar
Tips-Forge-1.20.1-12.1.8.jar
ToastControl-1.20.1-8.0.3.jar
toms-peripherals-1.20.1-1.2.1.jar
TravelersTitles-1.20-Forge-4.0.2.jar
Tropicraft-9.6.3.jar
Twigs-1.20.1-3.1.0.jar
twilightforest-1.20.1-4.3.2508-universal.jar
voicechat-forge-1.20.1-2.5.18.jar
watut-forge-1.20.1-1.1.3.jar
WitherSkeletonTweaks-1.20.1-9.1.0.jar
worldedit-mod-7.2.15.jar
world_preview-forge-1.20.1-1.3.1.jar
WWOO-FABRIC+FORGE+QUILT-2.0.0.jar
YungsApi-1.20-Forge-4.0.6.jar
YungsBetterDesertTemples-1.20-Forge-3.0.3.jar
YungsBetterDungeons-1.20-Forge-4.0.4.jar
YungsBetterEndIsland-1.20-Forge-2.0.6.jar
YungsBetterJungleTemples-1.20-Forge-2.0.5.jar
YungsBetterMineshafts-1.20-Forge-4.0.4.jar
YungsBetterNetherFortresses-1.20-Forge-2.0.6.jar
YungsBetterOceanMonuments-1.20-Forge-3.0.4.jar
YungsBetterStrongholds-1.20-Forge-4.0.3.jar
YungsBetterWitchHuts-1.20-Forge-3.0.3.jar
YungsExtras-1.20-Forge-4.0.3.jar
Zeta-1.0-24.jar
[1.20.1]davesbuilds.jar

As of last time, if you need an instance zip I can provide upon request

**Comment by thedirptastic** [comment]
Thats odd. When I was testing it originally, it appeared to work, but testing it now, it doesn't. I'll get a fix out this week

**Comment by thedirptastic** [comment]
It has been fixed. I will release a patch on modrinth and curseforge once I fix fall damage.
